name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  node-ci:
    uses: stillsystems/.github/.github/workflows/reusable-node-ci.yml@main
    with:
      node-version: '20.x'
      run-xvfb: true
